filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "logs-hsn"

setup.ilm.enabled: false
setup.template.name: "logs-hsn"
setup.template.pattern: "logs-hsn"
setup.dashboards.index: "logs-hsn"

setup.kibana:
  host: "kibana:5601"
